export const GAME_START = 'GAME_START';
export const GAME_START_REQUESTED = 'GAME_START_REQUESTED';
export const GAME_STOP = 'GAME_STOP';
export const GAME_STOP_REQUESTED = 'GAME_STOP_REQUESTED';

export const SCORE_INCREMENT = 'SCORE_INCREMENT';
export const LIVES_DECREMENT = 'LIVES_DECREMENT';

export const TARGET_RESET = 'TARGET_RESET';
export const TARGET_SPAWN = 'TARGET_SPAWN';
export const TARGET_DECREMENT = 'TARGET_DECREMENT';
export const TARGET_DESTROY = 'TARGET_DESTROY';
export const TARGET_DESTROY_REQUESTED = 'TARGET_DESTROY_REQUESTED';
export const TARGET_SPAWN_PER_SECOND = 'TARGET_SPAWN_PER_SECOND';
export const TARGET_SPAWN_PER_SECOND_REQUESTED =
  'TARGET_SPAWN_PER_SECOND_REQUESTED';

export const SELF_TARGET_DESTROY_REQUESTED = 'SELF_TARGET_DESTROY_REQUESTED';
